name: main CI
on: [push]
jobs:
  dire_bonjour:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - run: sudo apt-get update && sudo apt-get install -y asciidoctor
      - run: make all
      - run: ls -la
      - run: netlify deploy --dir=./dist/