name: main CI
on: [push]
jobs:
  main-CI:
    runs-on: ubuntu-20.04
    steps:
      
      - uses: actions/checkout@v2
      - run: sudo apt-get update && sudo apt-get install -y asciidoctor
      - run: make all
      - run: ls -la
      - run: netlify deploy --prod --dir=./dist/
        env:
          NETLIFY_AUTH_TOKEN:  ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{secrets.NETLIFY_SITE_ID}}
